site_name: MKDocs Test Deployment
# site_url: https://KCerveny.github.io/Test-Docs-Repo/
nav:
  - Home: index.md
  - Setup: howto.md
theme:
  name: material
  logo: assets/arrow_wordmark_gray.svg
  favicon: assets/favicon.png
  features:
    - header.autohide
    - nagivation.footer
  palette:
    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/theme-light-dark
    #     name: Switch to light mode

    # Light mode scheme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode scheme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/fab4bxaAW9
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/ArrowAir_
    - icon: fontawesome/brands/github
      link: https://github.com/Arrow-air

plugins:
  - offline