site_name: MKDocs Test Deployment
# site_url: https://KCerveny.github.io/Test-Docs-Repo/
nav:
  - Home: index.md
  - Setup: howto.md
theme:
  name: material
  logo: assets/arrow_wordmark_gray.svg
  favicon: assets/favicon.png
  features:
    - header.autohide
    - nagivation.footer
  palette:
    # Light mode scheme
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode scheme
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/fab4bxaAW9
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/ArrowAir_
    - icon: fontawesome/brands/github
      link: https://github.com/Arrow-air

